services:
  mongo:
    image: mongo:8.2.3
    container_name: mongo8
    restart: "no"
    environment:
      MONGO_INITDB_ROOT_USERNAME: student
      MONGO_INITDB_ROOT_PASSWORD: secret123
      MONGO_INITDB_DATABASE: playground
      TZ: Asia/Tokyo
    ports:
      - "27017:27017"
    volumes:
      - mongo8_data:/data/db

  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    container_name: mongo-express
    restart: "no"
    depends_on:
      mongo:
        condition: service_started
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_BASICAUTH: "false"
      ME_CONFIG_MONGODB_URL: mongodb://student:secret123@mongo:27017/admin

volumes:
  mongo8_data:
